### ISSUE TITLE
Can't Call Service with Multiple Data Items

### ISSUE THREAD

**Issue by hiszd** [jaybz/TP-HomeAssistant#12]
I have an issue where I am trying to call a service, but under "Data:" I can only enter one line. Because of this the service does not execute properly. I need to be able to have multiple lines in this field so the YAML makes sense to HA.

**Comment by jaybz** [comment]
That field isn't used for YAML. It needs to be in JSON format which can all be in one line. I know that isn't easily readable but it's a limitation of Touch Portal rather than the plugin and there isn't anything a plugin can do about that field yet.
