### ISSUE TITLE
Add entity sorting and filtering

### ISSUE THREAD

**Issue by jaybz** [jaybz/TP-HomeAssistant#13]
~~Based on a few tests, this will only work on the first time the plugin loads as entity removal doesn't appear to work at the moment. The only way to re-apply sorting and filtering (eg. when new entities are added or the filter is changed) is to restart Touch Portal. As I plan on performing a rewrite/refactor of the plugin soon-ish, I won't be investigating the entity removal issue until after that is done. For now, this will be implemented only on the first plugin load after Touch Portal is started.~~

**Comment by jaybz** [comment]
A couple more caveats:

- Changing filtering options will break existing buttons/events/flows that use entities that are filtered out. Plugins are not able to hide states from the Touch Portal UI while still allowing buttons/events/flows that use those states to work.
- The plugin is currently only able to control the order at which states are created for that particular plugin. Touch Portal ultimately controls how these states are presented in the UI and Touch Portal currently orders them in the UI in the same order as they are created. It is possible for multiple plugins to send state creation commands to Touch Portal at the same time, causing their states to be interleaved in Touch Portal UI elements where the plugin states aren't grouped. This is particularly likely to happen to plugins that have a lot of dynamic states like the HA plugin when you have a lot of entities, for example. A screenshot of that happening is below. ~~There may be a way to deal with this on the plugin's end, however, refactoring the API abstraction library (and as a result the plugin itself) is likely required.~~ I will be including a way to manually remove all the states and recreate them. This will hopefully move all Home Assistant states to the bottom of affected Touch Portal UI elements.

![image](https://user-images.githubusercontent.com/10665566/148726490-6810390f-aecb-4b17-a7c1-c783e08e762b.png)

**Comment by jaybz** [comment]
I accidentally found why state removal wasn't working. I've stricken through information in the previous comments that are no longer applicable as a result.

**Comment by mrhyde1st** [comment]
Sorry, not an any way decent programmer, but as an idea for sorting could you run the options in the drop-list via a Quicksort algorithm, pop it into an array, then if needed at the end just create a second array (to which the drop-down is pinned), which cycles through the sorted array, so that creation order for that array is technically the sorted version?

**Comment by jaybz** [comment]
@mrhyde1st the problem is that the plugin has no control over the drop-down rendering or access to any of the lists that are used for populating that drop-down. The plugins have zero visibility into actual objects being used by Touch Portal for tracking these states or rendering the UI. Plugins also cannot prevent Touch Portal from processing state creation commands from other plugins either or prevent the other plugins themselves from sending those commands.

**Comment by jaybz** [comment]
I've released [0.9.8](https://github.com/jaybz/TP-HomeAssistant/releases/tag/0.9.8) which adds sorting, filtering, and a new action which rebuilds (deletes and re-creates) all HA states. Please see the [README](https://github.com/jaybz/TP-HomeAssistant/blob/release/README.md) for how the new features work.

I'm keeping this issue open for now as the release is still marked as a pre-release. This is because I'm not satisfied with the testing I've done on the plugin so far. If there are any issues with the update, however, please post a new issue instead.

**Comment by jaybz** [comment]
I've also added an inclusion filter. Based on testing so far, I haven't found any issues, so it's time to close this issue. Note that there is an issue that appears to be inherent to the TouchPortalAPI library which can be triggered due to the filter settings. This isn't an issue with the filter settings itself so the issue will be tracked separately: #18
