### ISSUE TITLE
Windows 11 22H2 can't install 0.9.13

### ISSUE THREAD

**Issue by krftcz** [jaybz/TP-HomeAssistant#26]
I'm just trying out Touch Portal as an alternative to Stream Deck. I tried to install 0.9.13 as it is the latest version but it gets stuck on probably the last step. The progress bar is almost filled in and the step that gets stuck is "Importing win-x86/TP-HomeAssistant/Microsoft.Extensions.FileProviders.Abstractions.dll"

The previous version installed just fine. That's probably not all the info you need but feel free to ask for any additional details or please advise on what am I doing wrong. Keep up the good work.

**Comment by jaybz** [comment]
Looks like I screwed up something else on the build workflow. ~~I think I know exactly what the issue is though.~~ Thanks for the report.

EDIT: I've figured out exactly what the issue is with the build workflow. This is what I get for not testing on a clean system. I'm working on a fix now.

**Comment by jaybz** [comment]
Issue has been fixed and I've created a [re-release version](https://github.com/jaybz/TP-HomeAssistant/releases/tag/0.9.13-rerelease).
